apiVersion: apps/v1
kind: Deployment
metadata:
  name: fordwind-main-deploy
  namespace: default
  labels:
    app: web
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-app
          image: vkoshuk/k8sphp:v1
          ports:
            - containerPort: 80
